#
# A simple Makefile
#
all:: ; \
make -C FPL-lambda/JS -f Makefile all
#
testall:: ; \
make -C FPL-lambda/JS -f Makefile testall
#
cleanall:: ; \
make -C FPL-lambda/JS -f Makefile cleanall
#
# ###### end of [Makefile] ######
