#
# A simple Makefile
#

######

PATSCC=$(PATSHOME)/bin/patscc
PATSOPT=$(PATSHOME)/bin/patsopt

######

testall:: ; \
$(PATSCC) -tcats prop-logic.dats

######

clean:: ; rm -f *~

######

cleanall:: clean

###### end of [Makefile] ######
