#
# A simple Makefile
#
all:: ; \
make -C FPL-lambda -f Makefile all
all:: ; \
make -C FPL-lambda/JS -f Makefile all
#
testall:: ; \
make -C FPL-lambda -f Makefile testall
testall:: ; \
make -C FPL-lambda/JS -f Makefile testall
#
# ###### end of [Makefile] ######
