#
# A simple Makefile
#

######

PATSCC=$(PATSHOME)/bin/patscc
PATSOPT=$(PATSHOME)/bin/patsopt

######
#
testall:: ; $(PATSCC) -tcats fib.dats tally.dats
#
######

clean:: ; rm -f *~

######

cleanall:: clean

###### end of [Makefile] ######
